-- Stores one Facenet512 embedding per verified identity (Issue 2). One row per
-- identity_id: EmbeddingStore overwrites on re-enrollment rather than duplicating,
-- consistent with the 1:1 recheck design (no 1:N face identification in scope).
--
-- "GENERATED BY DEFAULT AS IDENTITY" (SQL:2003) is used instead of Postgres-only
-- BIGSERIAL so this migration runs unmodified against both the real Postgres
-- database and the H2 in-memory database used by the test profile.
CREATE TABLE identity_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id VARCHAR(255) NOT NULL UNIQUE,
    embedding TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
